### PR TITLE
fix(package): Fix node engine version range

### PR DESCRIPTION
**Pull request by matheuslc**
#39 Fix this issue

### CODE REVIEW

**Comment by adrianlee44** [comment]
Thanks for the PR. I'm looking into why your tests are failing but for the mean time, can you just update the node version to be only `>=5.3.0.

**Comment by matheuslc** [comment]
@adrianlee44 Awesome. I did it.

**Comment by adrianlee44** [comment]
Figured out the issue with the failing tests. It has nothing to do with the changes you are making so I'm going to go ahead and merge your PR.

**Comment by adrianlee44** [comment]
Thanks for the PR again

**Comment by matheuslc** [comment]
awesome @adrianlee44! Thank you!

**Pull request merged**
